"""Default policy parameters; generated observations are not bundled."""

DEFAULT_POLICY = {'schema_version': 1,
 'design_name': 'Expanded evaluation 2026-09-06',
 'status': 'Frozen original Q9 execution configuration',
 'design_contract': {'one_continuation_object_per_planner': True,
                     'current_task_reward_coefficient': 1.0,
                     'hidden_workload_access_before_arrival': False,
                     'guidance_applies_only_to_lp_opportunity': True,
                     'route_and_arrival_signature_must_match': True},
 'default_methods': ['CMSACR'],
 'unified_methods': {'CMSACR': {'method_key': 'cmsacr',
                                'label': 'CMSACR',
                                'action_rule': 'mode_separated',
                                'continuation': {'support_rule': 'gh',
                                                 'support_order': 9,
                                                 'beam_width': 8,
                                                 'lookahead_depth': 8,
                                                 'cache_expected_stats': True,
                                                 'guidance': {'rule': 'blended',
                                                              'weight': 0.5}}}},
 'legacy_methods': {},
 'control_methods': {'mean': 'Mean Workload',
                     'saa5': 'SAA 5',
                     'one_step': 'One Step EV',
                     'greedy': 'Greedy Density',
                     'nearest': 'Nearest First',
                     'priority': 'Highest Priority'}}
