% Historical MATLAB draft of the decomposition illustration.
% The final figure was subsequently edited in PowerPoint.
% This draft contains older beam-search labels and does not reproduce
% the final framework or implement its numerical experiments.
% plot.py renders the final authored illustration.

clc;
clear;
close all;

%% Figure
fig = figure( ...
    'Color', 'w', ...
    'Position', [100, 100, 1450, 650]);

ax = axes('Position', [0 0 1 1]);
axis(ax, [0 1 0 1]);
axis off;
hold on;

%% ------------------------------------------------------------
%  Box positions: [x, y, width, height]
% -------------------------------------------------------------

% Original problem
boxMTE = [0.035, 0.36, 0.185, 0.27];

% Decomposed problems
boxTop = [0.315, 0.63, 0.225, 0.25];
boxSub = [0.315, 0.13, 0.225, 0.25];

% Solution boxes
boxTopSol = [0.675, 0.61, 0.275, 0.29];
boxSubSol = [0.675, 0.11, 0.275, 0.29];

%% ------------------------------------------------------------
%  Five main boxes
% -------------------------------------------------------------

addBox(boxMTE, { ...
    '\bf Problem (MTE)', ...
    '', ...
    'Maximize the expected', ...
    'priority-weighted number', ...
    'of completed tasks', ...
    '', ...
    '\bf Decisions:', ...
    'r_{k+1}, x_i, a_i, f_i^u' ...
    }, 12.5);

addBox(boxTop, { ...
    '\bf Problem (MTE Top)', ...
    '', ...
    'Select the next task', ...
    '', ...
    'Maximize the estimated', ...
    'mission value', ...
    '', ...
    '\bf Decision:  r_{k+1}' ...
    }, 12.5);

addBox(boxSub, { ...
    '\bf Problem (MTE Sub)', ...
    '', ...
    'Select the execution action', ...
    '', ...
    'Maximize the remaining', ...
    'time and energy', ...
    '', ...
    '\bf Decisions:  x_i, a_i, f_i^u' ...
    }, 12.5);

addBox(boxTopSol, { ...
    '\bf Solution of MTE Top', ...
    '', ...
    'Two-task distribution evaluation', ...
    'for short-term value', ...
    '', ...
    'LP-guided beam search', ...
    'for future value', ...
    '', ...
    '\bf Obtain:  r_{k+1}^*' ...
    }, 12.0);

addBox(boxSubSol, { ...
    '\bf Solution of MTE Sub', ...
    '', ...
    'Derive the workload-action rule', ...
    '', ...
    'C_i:  Local / MEC / Skip', ...
    '', ...
    '\bf Obtain:', ...
    'x_i^*, a_i^*, f_i^{u,*}' ...
    }, 12.0);

%% ------------------------------------------------------------
%  MTE -> Top / Sub
%  Use a split connector similar to the reference figure
% -------------------------------------------------------------

% Right center of MTE box
xMTE = boxMTE(1) + boxMTE(3);
yMTE = boxMTE(2) + boxMTE(4)/2;

% Split position
xSplit = 0.267;

% Centers of Top and Sub
yTop = boxTop(2) + boxTop(4)/2;
ySub = boxSub(2) + boxSub(4)/2;

% Horizontal line from MTE
annotation('line', ...
    [xMTE xSplit], ...
    [yMTE yMTE], ...
    'LineWidth', 1.3);

% Vertical split
annotation('line', ...
    [xSplit xSplit], ...
    [ySub yTop], ...
    'LineWidth', 1.3);

% Arrow to Top
annotation('arrow', ...
    [xSplit boxTop(1)], ...
    [yTop yTop], ...
    'LineWidth', 1.3, ...
    'HeadLength', 8, ...
    'HeadWidth', 8);

% Arrow to Sub
annotation('arrow', ...
    [xSplit boxSub(1)], ...
    [ySub ySub], ...
    'LineWidth', 1.3, ...
    'HeadLength', 8, ...
    'HeadWidth', 8);

%% Online decomposition label
addPlainText( ...
    [0.225, 0.465, 0.15, 0.055], ...
    'Online decomposition', ...
    12.5, ...
    'bold');

%% ------------------------------------------------------------
%  Top -> Top solution
% -------------------------------------------------------------

annotation('arrow', ...
    [boxTop(1)+boxTop(3), boxTopSol(1)], ...
    [yTop, boxTopSol(2)+boxTopSol(4)/2], ...
    'LineWidth', 1.3, ...
    'HeadLength', 8, ...
    'HeadWidth', 8);

%% ------------------------------------------------------------
%  Sub -> Sub solution
% -------------------------------------------------------------

annotation('arrow', ...
    [boxSub(1)+boxSub(3), boxSubSol(1)], ...
    [ySub, boxSubSol(2)+boxSubSol(4)/2], ...
    'LineWidth', 1.3, ...
    'HeadLength', 8, ...
    'HeadWidth', 8);

%% ------------------------------------------------------------
%  Interaction between Top solution and Sub solution
% -------------------------------------------------------------

% Two separate vertical arrows
xArrowUp   = 0.785;
xArrowDown = 0.875;

topBottom = boxTopSol(2);
subTop    = boxSubSol(2) + boxSubSol(4);

% Upward arrow:
% Sub solution -> Top solution
annotation('arrow', ...
    [xArrowUp xArrowUp], ...
    [subTop topBottom], ...
    'LineWidth', 1.3, ...
    'HeadLength', 8, ...
    'HeadWidth', 8);

% Downward arrow:
% Top solution -> Sub solution
annotation('arrow', ...
    [xArrowDown xArrowDown], ...
    [topBottom subTop], ...
    'LineWidth', 1.3, ...
    'HeadLength', 8, ...
    'HeadWidth', 8);

%% Labels for interaction arrows

% Upward information
addPlainText( ...
    [0.688, 0.455, 0.095, 0.105], ...
    {'Workload-action', ...
     'rule and', ...
     'execution cost'}, ...
    10.5, ...
    'normal');

% Downward information
addPlainText( ...
    [0.882, 0.455, 0.09, 0.085], ...
    {'Selected task', ...
     'r_{k+1}^*'}, ...
    10.5, ...
    'normal');

%% ------------------------------------------------------------
%  Figure caption
% -------------------------------------------------------------

addPlainText( ...
    [0.04, 0.015, 0.90, 0.055], ...
    'Fig. X. Online decomposition and solution framework for the MTE problem.', ...
    12.5, ...
    'normal');

%% ------------------------------------------------------------
%  Optional export
% -------------------------------------------------------------

% High-resolution PNG:
% exportgraphics(fig, ...
%     'MTE_online_decomposition.png', ...
%     'Resolution', 600);

% Vector PDF:
% exportgraphics(fig, ...
%     'MTE_online_decomposition.pdf', ...
%     'ContentType', 'vector');

%% ============================================================
%  Local functions
% ============================================================

function addBox(pos, textLines, fontSize)

    annotation('textbox', pos, ...
        'String', textLines, ...
        'Interpreter', 'tex', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Times New Roman', ...
        'FontSize', fontSize, ...
        'FontWeight', 'normal', ...
        'LineWidth', 1.15, ...
        'EdgeColor', [0.15 0.15 0.15], ...
        'BackgroundColor', 'white', ...
        'FitBoxToText', 'off', ...
        'Margin', 6);

end

function addPlainText(pos, txt, fontSize, fontWeight)

    annotation('textbox', pos, ...
        'String', txt, ...
        'Interpreter', 'tex', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Times New Roman', ...
        'FontSize', fontSize, ...
        'FontWeight', fontWeight, ...
        'LineStyle', 'none', ...
        'FitBoxToText', 'off', ...
        'Margin', 1);

end